name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - nodejs=18
  - jupyter_server
  - jupyterlite-core >=0.1.0,<0.2.0
  - pip:
    - voici==0.4.4
    - jupyterlite-xeus-python==0.8.1
