name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - nodejs=18
  - jupyter_server
  - jupyterlab-night
  - jupyterlab-language-pack-fr-FR
  - jupyterlite-core>=0.2.0a4
  - pip:
    - voici==0.4.4
    - jupyterlite-xeus-python==v1.0.0a0
